// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rptpzlujoqxthmehjjrw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJwdHB6bHVqb3F4dGhtZWhqanJ3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYyODUwOTAsImV4cCI6MjA3MTg2MTA5MH0.VmYGOlwpBDLO3bmqw_j0PdJJ0SY5rtnGAOhbO9259sI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});